### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by kyo-git** [kyo-git/chat-space#11]
# IPアドレス
18.177.111.167

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
サイドバーのユーザー名の付近のみ、背景色が異なる
[![Image from Gyazo](https://i.gyazo.com/50d723454e444d8ae9d73b546447f294.png)](https://gyazo.com/50d723454e444d8ae9d73b546447f294)

参照カリキュラム
https://master.tech-camp.in/curriculums/3944

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by kyo-git** [comment]
背景色の設定を削除しました

**Comment by naru6117** [comment]
ご提出と修正ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by kyo-git** [comment]
ありがとうございます！
